[package]
name = "rulog-cli"
version = "0.1.2"
edition = "2021"

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"

  [dependencies.rulog-core]
  path = "../rulog-core"

  [dependencies.rulog-vm]
  path = "../rulog-vm"
