[package]
name = "rulog-vm"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
env_logger = "0.10.1"
log = "0.4.20"

  [dependencies.rulog-core]
  path = "../rulog-core"
